# Generated by Django 3.2.4 on 2021-11-02 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20211021_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='user_linked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='totalAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('user_linked', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
