# Generated by Django 3.2.4 on 2022-01-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_expense_user_linked'),
    ]

    operations = [
        migrations.CreateModel(
            name='testExpenseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('incomeOrexpense', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('saving', 'Saving')], max_length=7)),
                ('amount_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
